### ISSUE TITLE
SSA: Is there any easy way to regenerate this stack-based SSA code back to CIL? 

### ISSUE THREAD

**Issue by lfkdsk** [m-carrasco/net-ssa#15]
Is there any easy way to regenerate this stack-based SSA code back to CIL? 
Maybe it's a good start to write an `IL => IL` optimizer.

> whatever, cool job ~

**Comment by m-carrasco** [comment]
> whatever, cool job ~

Thanks!

**Comment by lfkdsk** [comment]
Thanks for such a detailed reply. @m-carrasco 

> From what I understand, CIL bytecode is optimized by the JIT compiler. You could try to implement your optimisations there, perhaps.

Unfortunately, I'm working with a kind of C# aot backend (just like Unity's il2cpp backend), thus I cannot get benefits from the jit engine.  So I'm trying to build an `IL => IL` optimizer to resolve CIL before aot compile.

**Comment by m-carrasco** [comment]
If AOT is used rather than JIT, it is possible to apply even more aggressive optimisations. What sort of optimisation would you like to apply?

**Comment by lfkdsk** [comment]
Acctually, Aot engine is only do translate work (il => cpp) now. So I'd like to design a compile pipeline to resolve il cfg and it could write some opt-passes with cfg. But if this optimizer want to do more flow analysis, I'd like to build il to ssa formal to apply more ssa algos like LLVM's passes (devirtual,  partical inline ...).

**Comment by m-carrasco** [comment]
Thanks for sharing your motivation. I'd say that possibly all of these optimisations happen when the cpp is compiled. As an alternative, you could take a look at Roslyn's source code.

I'll close the issue but feel free to open it again.
